# Generated by Django 5.2 on 2025-12-08 11:55

import fotoapp.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotoapp', '0008_remove_session_cover_image_session_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to=fotoapp.models.photo.watermarked_directory_path, verbose_name='Wersja z logo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=fotoapp.models.photo.session_directory_path, verbose_name='Oryginał'),
        ),
    ]
